name: Nightly

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron:  '0 4 * * *'

jobs:

    Jazzy:
        uses: micro-ROS/micro_ros_setup/.github/workflows/ci.yml@jazzy

    Rolling:
        uses: micro-ROS/micro_ros_setup/.github/workflows/ci.yml@rolling

    Humble:
        uses: micro-ROS/micro_ros_setup/.github/workflows/ci.yml@humble

    Iron:
        uses: micro-ROS/micro_ros_setup/.github/workflows/ci.yml@iron
